apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    application: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0.28
    imagePullPolicy: IfNotPresent
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: root_pw
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: user
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: user_pw
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: db_name
    resources:
      requests:
        memory: "516Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "250m"
    livenessProbe:
      initialDelaySeconds: 10
      exec:
        command:
        - cat
        - /tmp/healthy 
      periodSeconds: 20
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 30
      httpGet:
        path: /
        port: 3306
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
